services:
    db:
        image: postgres:16-alpine
        container_name: segfault_db_prod
        restart: unless-stopped
        environment:
            POSTGRES_USER: segfault
            POSTGRES_PASSWORD: segfault
            POSTGRES_DB: segfault
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - secure_net
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: segfault_backend_prod
        restart: unless-stopped
        depends_on:
            - db
        environment:
            NODE_ENV: production
            DATABASE_URL: postgresql://segfault:segfault@db:5432/segfault
            JWT_SECRET: "mon_secret_jwt_super_long_et_complexe"
            JWT_EXPIRATION: "15m"
            REFRESH_EXPIRATION: "7d"
            FRONTEND_URL: http://localhost:8080
        volumes:
            - ./backend/certs:/app/certs:ro
        ports:
            - "4000:4000"
        networks:
            - secure_net
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: segfault_frontend_prod
        restart: unless-stopped
        depends_on:
            - backend
        ports:
            - "8080:80"
        networks:
            - secure_net
    adminer:
        image: adminer:latest
        container_name: segfault_adminer_prod
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "8081:8080"
        environment:
            - ADMINER_DEFAULT_SERVER=db
        networks:
            - secure_net
volumes:
    db_data:
networks:
    secure_net:
