version: "3.9"
services:
    db:
        image: postgres:16-alpine
        container_name: segfault_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: segfault
            POSTGRES_PASSWORD: segfault
            POSTGRES_DB: segfault
        volumes:
            - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - db_data:/var/lib/postgresql/data
        ports:
            - "5440:5432"
    adminer:
        image: adminer
        container_name: segfault_adminer
        restart: unless-stopped
        ports:
            - "8080:8080"
volumes:
    db_data:
